### PR TITLE
Update GAF.yaml with temporary Xenbase GAF location

### PR DESCRIPTION
**Pull request by christabone**
Added temporary GAF location to for Xenbase. This will be updated once GO finishes their Xenbase production pipeline. Adding it from Xenbase directly will allow @valearna do begin work on the automated gene descriptions while we wait for GO.

### CODE REVIEW

**Review by sierra-moxon — APPROVED** [review]
Before this goes to production, we would like the GAF to come from GO (there are validation steps that take place at GO that are still in progress) - please coordinate with @kltm on deadlines for this. :)

**Comment by christabone** [comment]
Thanks @sierra-moxon! 

Just looking over our email exchange and we spoke with @kltm directly about the whole process. Unfortunately it appears you weren't CC'ed. This PR is just a stopgap so @valearna has data to play with before the pipeline is finished.

**Comment by kltm** [comment]
We've added it to the TODO list for finalizing Xenbase in GO https://github.com/orgs/geneontology/projects/60#card-84631846

**Comment by christabone** [comment]
If this GAF doesn't work for whatever reason, I'll revert the PR. The hope is just for some test data in the meantime.

**Comment by christabone** [comment]
Re-opening to hopefully trigger GitHub actions test.

**Comment by kltm** [comment]
@christabone  @sierra-moxon Xenbase is now part of the official GO release and can URLs can be updated. Not sure if there is a ticket I should as this to...?

**Comment by christabone** [comment]
@kltm Thanks so much! Would it be possible to post the URL to this ticket? 

https://agr-jira.atlassian.net/browse/KANBAN-245

I can open a PR to the Ferret program to grab the data overnight.

**Pull request merged**
